import type { CandidateProfile, VacancyProfile, APIClient } from '@/lib/types';

// Mock candidates (candidate-centric: one row per unique candidate)
export const mockCandidates: CandidateProfile[] = [
  {
    id: 'cand-1',
    name: 'Jan Janssen',
    email: 'jan.janssen@email.com',
    phone: '+32 470 12 34 56',
    status: 'qualified',
    availability: 'immediate',
    shiftPreference: ['day', 'evening'],
    skills: ['Reachtruck', 'Orderpicking', 'Nederlands', 'Frans'],
    certifications: ['VCA', 'Rijbewijs B'],
    rating: 4.5,
    linkedVacancies: [
      { vacancyId: 'v1', vacancyTitle: 'Magazijnier', company: 'ITZU Kortrijk', applicationStatus: 'placed', score: 85, appliedAt: '2025-06-16T09:30:00Z' },
      { vacancyId: 'v3', vacancyTitle: 'Orderpicker', company: 'ITZU Antwerpen', applicationStatus: 'applied', score: null, appliedAt: '2026-02-10T10:30:00Z' },
    ],
    interactions: [
      { id: 'int-1-1', type: 'registered', title: 'Kandidaat geregistreerd', timestamp: '2025-06-15T10:00:00Z' },
      { id: 'int-1-2', type: 'applied', title: 'Gesolliciteerd', description: 'Via WhatsApp', vacancyId: 'v1', vacancyTitle: 'Magazijnier', timestamp: '2025-06-16T09:30:00Z' },
      { id: 'int-1-3', type: 'prescreening_started', title: 'Pre-screening gestart', vacancyId: 'v1', vacancyTitle: 'Magazijnier', timestamp: '2025-06-16T09:31:00Z' },
      { id: 'int-1-4', type: 'prescreening_completed', title: 'Pre-screening afgerond', description: 'Score: 85/100 - Gekwalificeerd', vacancyId: 'v1', vacancyTitle: 'Magazijnier', timestamp: '2025-06-16T09:45:00Z' },
      { id: 'int-1-5', type: 'interview_scheduled', title: 'Interview ingepland', description: '18 juni 2025 om 14:00', vacancyId: 'v1', vacancyTitle: 'Magazijnier', timestamp: '2025-06-17T11:00:00Z' },
      { id: 'int-1-6', type: 'interview_completed', title: 'Interview afgerond', description: 'Positieve indruk', vacancyId: 'v1', vacancyTitle: 'Magazijnier', timestamp: '2025-06-18T15:00:00Z' },
      { id: 'int-1-7', type: 'submitted_to_client', title: 'Voorgesteld aan klant', vacancyId: 'v1', vacancyTitle: 'Magazijnier', timestamp: '2025-06-19T09:00:00Z' },
      { id: 'int-1-8', type: 'placed', title: 'Geplaatst', description: 'Startdatum: 1 juli 2025', vacancyId: 'v1', vacancyTitle: 'Magazijnier', timestamp: '2025-06-25T14:00:00Z' },
      { id: 'int-1-9', type: 'applied', title: 'Gesolliciteerd', description: 'Via CV upload', vacancyId: 'v3', vacancyTitle: 'Orderpicker', timestamp: '2026-02-10T10:30:00Z' },
    ],
    createdAt: '2025-06-15T00:00:00Z',
    lastActivityAt: '2026-02-10T10:30:00Z',
  },
  {
    id: 'cand-2',
    name: 'Marie Peeters',
    email: 'marie.peeters@email.com',
    phone: '+32 471 23 45 67',
    status: 'placed',
    availability: 'not_available',
    shiftPreference: ['day', 'night'],
    skills: ['Heftruckchauffeur', 'Reachtruck', 'Nederlands', 'Engels'],
    certifications: ['VCA', 'Rijbewijs B', 'Rijbewijs C'],
    rating: 4.8,
    linkedVacancies: [
      { vacancyId: 'v2', vacancyTitle: 'Heftruckchauffeur', company: 'ITZU Gent', applicationStatus: 'placed', score: 92, appliedAt: '2025-07-21T14:00:00Z' },
    ],
    interactions: [
      { id: 'int-2-1', type: 'registered', title: 'Kandidaat geregistreerd', timestamp: '2025-07-20T08:00:00Z' },
      { id: 'int-2-2', type: 'applied', title: 'Gesolliciteerd', description: 'Via Voice call', vacancyId: 'v2', vacancyTitle: 'Heftruckchauffeur', timestamp: '2025-07-21T14:00:00Z' },
      { id: 'int-2-3', type: 'prescreening_started', title: 'Pre-screening gestart', vacancyId: 'v2', vacancyTitle: 'Heftruckchauffeur', timestamp: '2025-07-21T14:01:00Z' },
      { id: 'int-2-4', type: 'prescreening_completed', title: 'Pre-screening afgerond', description: 'Score: 92/100 - Gekwalificeerd', vacancyId: 'v2', vacancyTitle: 'Heftruckchauffeur', timestamp: '2025-07-21T14:25:00Z' },
      { id: 'int-2-5', type: 'submitted_to_client', title: 'Voorgesteld aan klant', vacancyId: 'v2', vacancyTitle: 'Heftruckchauffeur', timestamp: '2025-07-22T10:00:00Z' },
      { id: 'int-2-6', type: 'placed', title: 'Geplaatst', description: 'Startdatum: 1 augustus 2025', vacancyId: 'v2', vacancyTitle: 'Heftruckchauffeur', timestamp: '2026-02-09T14:25:00Z' },
    ],
    createdAt: '2025-07-20T00:00:00Z',
    lastActivityAt: '2026-02-09T14:25:00Z',
  },
  {
    id: 'cand-3',
    name: 'Pieter De Smet',
    email: 'pieter.desmet@email.com',
    phone: '+32 472 34 56 78',
    status: 'new',
    availability: '1_week',
    shiftPreference: ['day'],
    skills: ['Magazijnwerk', 'Nederlands'],
    certifications: [],
    rating: null,
    linkedVacancies: [
      { vacancyId: 'v1', vacancyTitle: 'Magazijnier', company: 'ITZU Kortrijk', applicationStatus: 'screening', score: null, appliedAt: '2026-02-09T11:05:00Z' },
    ],
    interactions: [
      { id: 'int-3-1', type: 'registered', title: 'Kandidaat geregistreerd', timestamp: '2026-02-09T11:00:00Z' },
      { id: 'int-3-2', type: 'applied', title: 'Gesolliciteerd', description: 'Via WhatsApp', vacancyId: 'v1', vacancyTitle: 'Magazijnier', timestamp: '2026-02-09T11:05:00Z' },
      { id: 'int-3-3', type: 'prescreening_started', title: 'Pre-screening gestart', vacancyId: 'v1', vacancyTitle: 'Magazijnier', timestamp: '2026-02-09T11:06:00Z' },
    ],
    createdAt: '2026-02-09T00:00:00Z',
    lastActivityAt: '2026-02-09T11:20:00Z',
  },
  {
    id: 'cand-4',
    name: 'Sarah Van Den Berg',
    email: 'sarah.vdb@email.com',
    phone: '+32 473 45 67 89',
    status: 'qualified',
    availability: 'immediate',
    shiftPreference: ['day', 'evening', 'weekend'],
    skills: ['Orderpicking', 'Inpakken', 'Nederlands', 'Engels', 'Duits'],
    certifications: ['VCA'],
    rating: 4.2,
    linkedVacancies: [
      { vacancyId: 'v3', vacancyTitle: 'Orderpicker', company: 'ITZU Antwerpen', applicationStatus: 'submitted', score: 78, appliedAt: '2025-11-10T09:15:00Z' },
      { vacancyId: 'v5', vacancyTitle: 'Inpakker', company: 'ITZU Mechelen', applicationStatus: 'applied', score: null, appliedAt: '2026-02-08T09:15:00Z' },
    ],
    interactions: [
      { id: 'int-4-1', type: 'registered', title: 'Kandidaat geregistreerd', timestamp: '2025-11-10T09:00:00Z' },
      { id: 'int-4-2', type: 'applied', title: 'Gesolliciteerd', description: 'Via CV upload', vacancyId: 'v3', vacancyTitle: 'Orderpicker', timestamp: '2025-11-10T09:15:00Z' },
      { id: 'int-4-3', type: 'prescreening_completed', title: 'Pre-screening afgerond', description: 'Score: 78/100 - Gekwalificeerd', vacancyId: 'v3', vacancyTitle: 'Orderpicker', timestamp: '2025-11-10T09:30:00Z' },
      { id: 'int-4-4', type: 'interview_scheduled', title: 'Interview ingepland', description: '15 november 2025 om 10:00', vacancyId: 'v3', vacancyTitle: 'Orderpicker', timestamp: '2025-11-12T11:00:00Z' },
      { id: 'int-4-5', type: 'interview_completed', title: 'Interview afgerond', description: 'Goede kandidaat, meerdere talen', vacancyId: 'v3', vacancyTitle: 'Orderpicker', timestamp: '2025-11-15T11:00:00Z' },
      { id: 'int-4-6', type: 'submitted_to_client', title: 'Voorgesteld aan klant', vacancyId: 'v3', vacancyTitle: 'Orderpicker', timestamp: '2026-02-05T14:00:00Z' },
      { id: 'int-4-7', type: 'applied', title: 'Gesolliciteerd', description: 'Via WhatsApp', vacancyId: 'v5', vacancyTitle: 'Inpakker', timestamp: '2026-02-08T09:15:00Z' },
    ],
    createdAt: '2025-11-10T00:00:00Z',
    lastActivityAt: '2026-02-08T09:15:00Z',
  },
  {
    id: 'cand-5',
    name: 'Thomas Willems',
    email: 'thomas.willems@email.com',
    phone: '+32 474 56 78 90',
    status: 'new',
    availability: '2_weeks',
    shiftPreference: ['day', 'evening'],
    skills: ['Heftruckchauffeur', 'Nederlands'],
    certifications: ['Rijbewijs B'],
    rating: null,
    linkedVacancies: [
      { vacancyId: 'v2', vacancyTitle: 'Heftruckchauffeur', company: 'ITZU Gent', applicationStatus: 'screening', score: null, appliedAt: '2026-02-11T08:00:00Z' },
    ],
    interactions: [
      { id: 'int-5-1', type: 'registered', title: 'Kandidaat geregistreerd', timestamp: '2026-02-11T07:50:00Z' },
      { id: 'int-5-2', type: 'applied', title: 'Gesolliciteerd', description: 'Via Voice call', vacancyId: 'v2', vacancyTitle: 'Heftruckchauffeur', timestamp: '2026-02-11T08:00:00Z' },
      { id: 'int-5-3', type: 'prescreening_started', title: 'Pre-screening gestart', vacancyId: 'v2', vacancyTitle: 'Heftruckchauffeur', timestamp: '2026-02-11T08:01:00Z' },
    ],
    createdAt: '2026-02-11T00:00:00Z',
    lastActivityAt: '2026-02-11T08:00:00Z',
  },
  {
    id: 'cand-6',
    name: 'Lisa Martens',
    email: 'lisa.martens@email.com',
    phone: '+32 475 67 89 01',
    status: 'qualified',
    availability: 'immediate',
    shiftPreference: ['night', 'weekend'],
    skills: ['Productie', 'Machinebediening', 'Nederlands', 'Frans'],
    certifications: ['VCA', 'Rijbewijs B'],
    rating: 4.0,
    linkedVacancies: [
      { vacancyId: 'v4', vacancyTitle: 'Productie Operator', company: 'ITZU Brugge', applicationStatus: 'submitted', score: 88, appliedAt: '2025-09-01T10:15:00Z' },
    ],
    interactions: [
      { id: 'int-6-1', type: 'registered', title: 'Kandidaat geregistreerd', timestamp: '2025-09-01T10:00:00Z' },
      { id: 'int-6-2', type: 'applied', title: 'Gesolliciteerd', description: 'Via WhatsApp', vacancyId: 'v4', vacancyTitle: 'Productie Operator', timestamp: '2025-09-01T10:15:00Z' },
      { id: 'int-6-3', type: 'prescreening_completed', title: 'Pre-screening afgerond', description: 'Score: 88/100 - Gekwalificeerd', vacancyId: 'v4', vacancyTitle: 'Productie Operator', timestamp: '2025-09-01T10:45:00Z' },
      { id: 'int-6-4', type: 'note_added', title: 'Notitie toegevoegd', description: 'Ervaren operator met technische achtergrond', timestamp: '2025-09-02T09:00:00Z' },
      { id: 'int-6-5', type: 'submitted_to_client', title: 'Voorgesteld aan klant', vacancyId: 'v4', vacancyTitle: 'Productie Operator', timestamp: '2026-02-07T16:35:00Z' },
    ],
    createdAt: '2025-09-01T00:00:00Z',
    lastActivityAt: '2026-02-07T16:35:00Z',
  },
  {
    id: 'cand-7',
    name: 'Kevin Van Damme',
    email: 'kevin.vd@email.com',
    phone: '+32 476 78 90 12',
    status: 'inactive',
    availability: 'not_available',
    shiftPreference: ['day'],
    skills: ['Administratie', 'Excel', 'Nederlands', 'Engels'],
    certifications: [],
    rating: 3.5,
    linkedVacancies: [
      { vacancyId: 'v6', vacancyTitle: 'Administratief Bediende', company: 'ITZU Leuven', applicationStatus: 'rejected', score: 65, appliedAt: '2025-04-15T08:30:00Z' },
    ],
    interactions: [
      { id: 'int-7-1', type: 'registered', title: 'Kandidaat geregistreerd', timestamp: '2025-04-15T08:00:00Z' },
      { id: 'int-7-2', type: 'applied', title: 'Gesolliciteerd', description: 'Via CV upload', vacancyId: 'v6', vacancyTitle: 'Administratief Bediende', timestamp: '2025-04-15T08:30:00Z' },
      { id: 'int-7-3', type: 'prescreening_completed', title: 'Pre-screening afgerond', description: 'Score: 65/100 - Gekwalificeerd', vacancyId: 'v6', vacancyTitle: 'Administratief Bediende', timestamp: '2025-04-15T09:00:00Z' },
      { id: 'int-7-4', type: 'interview_scheduled', title: 'Interview ingepland', description: '20 april 2025 om 14:00', vacancyId: 'v6', vacancyTitle: 'Administratief Bediende', timestamp: '2025-04-16T10:00:00Z' },
      { id: 'int-7-5', type: 'interview_completed', title: 'Interview afgerond', description: 'Onvoldoende Excel kennis', vacancyId: 'v6', vacancyTitle: 'Administratief Bediende', timestamp: '2025-04-20T15:00:00Z' },
      { id: 'int-7-6', type: 'rejected', title: 'Afgewezen', description: 'Niet voldoende technische vaardigheden', vacancyId: 'v6', vacancyTitle: 'Administratief Bediende', timestamp: '2026-01-20T10:00:00Z' },
    ],
    createdAt: '2025-04-15T00:00:00Z',
    lastActivityAt: '2026-01-20T10:00:00Z',
  },
  {
    id: 'cand-8',
    name: 'Emma Claessens',
    email: 'emma.claessens@email.com',
    phone: '+32 477 89 01 23',
    status: 'qualified',
    availability: 'specific_date',
    availableFrom: '2026-03-01',
    shiftPreference: ['day', 'flexible'],
    skills: ['Magazijnwerk', 'Orderpicking', 'Reachtruck', 'Nederlands'],
    certifications: ['VCA', 'Rijbewijs B', 'Reachtruck certificaat'],
    rating: 4.7,
    linkedVacancies: [
      { vacancyId: 'v1', vacancyTitle: 'Magazijnier', company: 'ITZU Kortrijk', applicationStatus: 'applied', score: null, appliedAt: '2026-02-05T11:00:00Z' },
      { vacancyId: 'v3', vacancyTitle: 'Orderpicker', company: 'ITZU Antwerpen', applicationStatus: 'applied', score: null, appliedAt: '2026-02-06T14:30:00Z' },
      { vacancyId: 'v5', vacancyTitle: 'Inpakker', company: 'ITZU Mechelen', applicationStatus: 'submitted', score: 91, appliedAt: '2025-08-20T09:30:00Z' },
    ],
    interactions: [
      { id: 'int-8-1', type: 'registered', title: 'Kandidaat geregistreerd', timestamp: '2025-08-20T09:00:00Z' },
      { id: 'int-8-2', type: 'applied', title: 'Gesolliciteerd', description: 'Via CV upload', vacancyId: 'v5', vacancyTitle: 'Inpakker', timestamp: '2025-08-20T09:30:00Z' },
      { id: 'int-8-3', type: 'prescreening_completed', title: 'Pre-screening afgerond', description: 'Score: 91/100 - Gekwalificeerd', vacancyId: 'v5', vacancyTitle: 'Inpakker', timestamp: '2025-08-20T10:00:00Z' },
      { id: 'int-8-4', type: 'interview_scheduled', title: 'Interview ingepland', description: '25 augustus 2025 om 11:00', vacancyId: 'v5', vacancyTitle: 'Inpakker', timestamp: '2025-08-21T14:00:00Z' },
      { id: 'int-8-5', type: 'interview_completed', title: 'Interview afgerond', description: 'Uitstekende kandidaat met veel ervaring', vacancyId: 'v5', vacancyTitle: 'Inpakker', timestamp: '2025-08-25T12:00:00Z' },
      { id: 'int-8-6', type: 'submitted_to_client', title: 'Voorgesteld aan klant', vacancyId: 'v5', vacancyTitle: 'Inpakker', timestamp: '2025-09-01T09:00:00Z' },
      { id: 'int-8-7', type: 'note_added', title: 'Notitie toegevoegd', description: 'Kandidaat beschikbaar vanaf 1 maart 2026', timestamp: '2026-01-15T10:00:00Z' },
      { id: 'int-8-8', type: 'applied', title: 'Gesolliciteerd', description: 'Via WhatsApp', vacancyId: 'v1', vacancyTitle: 'Magazijnier', timestamp: '2026-02-05T11:00:00Z' },
      { id: 'int-8-9', type: 'applied', title: 'Gesolliciteerd', description: 'Via WhatsApp', vacancyId: 'v3', vacancyTitle: 'Orderpicker', timestamp: '2026-02-06T14:30:00Z' },
    ],
    createdAt: '2025-08-20T00:00:00Z',
    lastActivityAt: '2026-02-06T14:30:00Z',
  },
];

// Mock vacancies (vacancy-centric with linked candidates and events)
export const mockVacancies: VacancyProfile[] = [
  {
    id: 'v1',
    title: 'Magazijnier',
    company: 'ITZU Kortrijk',
    location: 'Kortrijk',
    description: 'Zoekt ervaren magazijnier voor voltijdse functie',
    status: 'screening_active',
    createdAt: '2026-01-15T00:00:00Z',
    hasScreening: true,
    hasOnboarding: true,
    isOnline: true,
    channels: { voice: false, whatsapp: true, cv: true },
    candidatesCount: 45,
    completedCount: 38,
    qualifiedCount: 24,
    lastActivityAt: '2026-02-10T10:30:00Z',
    linkedCandidates: [
      { candidateId: 'cand-1', candidateName: 'Jan Janssen', email: 'jan.janssen@email.com', phone: '+32 470 12 34 56', applicationStatus: 'placed', score: 85, appliedAt: '2025-06-16T09:30:00Z', channel: 'whatsapp' },
      { candidateId: 'cand-3', candidateName: 'Pieter De Smet', email: 'pieter.desmet@email.com', phone: '+32 472 34 56 78', applicationStatus: 'screening', score: null, appliedAt: '2026-02-09T11:05:00Z', channel: 'whatsapp' },
      { candidateId: 'cand-8', candidateName: 'Emma Claessens', email: 'emma.claessens@email.com', phone: '+32 477 89 01 23', applicationStatus: 'applied', score: null, appliedAt: '2026-02-05T11:00:00Z', channel: 'whatsapp' },
    ],
    events: [
      { id: 'ev-v1-1', type: 'created', title: 'Vacature aangemaakt', timestamp: '2026-01-15T00:00:00Z' },
      { id: 'ev-v1-2', type: 'screening_configured', title: 'Pre-screening geconfigureerd', description: '5 knockout en 8 kwalificerende vragen', timestamp: '2026-01-15T14:30:00Z' },
      { id: 'ev-v1-3', type: 'published', title: 'Vacature online gezet', timestamp: '2026-01-16T09:00:00Z' },
      { id: 'ev-v1-4', type: 'candidate_applied', title: 'Kandidaat gesolliciteerd', candidateId: 'cand-1', candidateName: 'Jan Janssen', timestamp: '2025-06-16T09:30:00Z' },
      { id: 'ev-v1-5', type: 'candidate_qualified', title: 'Kandidaat gekwalificeerd', candidateId: 'cand-1', candidateName: 'Jan Janssen', description: 'Score: 85/100', timestamp: '2025-06-16T09:45:00Z' },
      { id: 'ev-v1-6', type: 'candidate_submitted', title: 'Kandidaat voorgesteld', candidateId: 'cand-1', candidateName: 'Jan Janssen', timestamp: '2025-06-19T09:00:00Z' },
      { id: 'ev-v1-7', type: 'candidate_placed', title: 'Kandidaat geplaatst', candidateId: 'cand-1', candidateName: 'Jan Janssen', description: 'Startdatum: 1 juli 2025', timestamp: '2025-06-25T14:00:00Z' },
      { id: 'ev-v1-8', type: 'candidate_applied', title: 'Kandidaat gesolliciteerd', candidateId: 'cand-8', candidateName: 'Emma Claessens', timestamp: '2026-02-05T11:00:00Z' },
      { id: 'ev-v1-9', type: 'candidate_applied', title: 'Kandidaat gesolliciteerd', candidateId: 'cand-3', candidateName: 'Pieter De Smet', timestamp: '2026-02-09T11:05:00Z' },
    ],
  },
  {
    id: 'v2',
    title: 'Heftruckchauffeur',
    company: 'ITZU Gent',
    location: 'Gent',
    description: 'Reachtruck operator met ervaring gevraagd',
    status: 'screening_active',
    createdAt: '2026-01-20T00:00:00Z',
    hasScreening: true,
    hasOnboarding: false,
    isOnline: true,
    channels: { voice: true, whatsapp: true, cv: false },
    candidatesCount: 32,
    completedCount: 28,
    qualifiedCount: 15,
    lastActivityAt: '2026-02-09T14:25:00Z',
    linkedCandidates: [
      { candidateId: 'cand-2', candidateName: 'Marie Peeters', email: 'marie.peeters@email.com', phone: '+32 471 23 45 67', applicationStatus: 'placed', score: 92, appliedAt: '2025-07-21T14:00:00Z', channel: 'voice' },
      { candidateId: 'cand-5', candidateName: 'Thomas Willems', email: 'thomas.willems@email.com', phone: '+32 474 56 78 90', applicationStatus: 'screening', score: null, appliedAt: '2026-02-11T08:00:00Z', channel: 'voice' },
    ],
    events: [
      { id: 'ev-v2-1', type: 'created', title: 'Vacature aangemaakt', timestamp: '2026-01-20T00:00:00Z' },
      { id: 'ev-v2-2', type: 'screening_configured', title: 'Pre-screening geconfigureerd', timestamp: '2026-01-20T10:00:00Z' },
      { id: 'ev-v2-3', type: 'published', title: 'Vacature online gezet', timestamp: '2026-01-21T08:00:00Z' },
      { id: 'ev-v2-4', type: 'candidate_applied', title: 'Kandidaat gesolliciteerd', candidateId: 'cand-2', candidateName: 'Marie Peeters', timestamp: '2025-07-21T14:00:00Z' },
      { id: 'ev-v2-5', type: 'candidate_qualified', title: 'Kandidaat gekwalificeerd', candidateId: 'cand-2', candidateName: 'Marie Peeters', description: 'Score: 92/100', timestamp: '2025-07-21T14:25:00Z' },
      { id: 'ev-v2-6', type: 'candidate_placed', title: 'Kandidaat geplaatst', candidateId: 'cand-2', candidateName: 'Marie Peeters', description: 'Startdatum: 1 augustus 2025', timestamp: '2026-02-09T14:25:00Z' },
      { id: 'ev-v2-7', type: 'candidate_applied', title: 'Kandidaat gesolliciteerd', candidateId: 'cand-5', candidateName: 'Thomas Willems', timestamp: '2026-02-11T08:00:00Z' },
    ],
  },
  {
    id: 'v3',
    title: 'Orderpicker',
    company: 'ITZU Antwerpen',
    location: 'Antwerpen',
    description: 'Orderpicker voor e-commerce warehouse',
    status: 'screening_active',
    createdAt: '2026-02-01T00:00:00Z',
    hasScreening: true,
    hasOnboarding: true,
    isOnline: true,
    channels: { voice: false, whatsapp: true, cv: true },
    candidatesCount: 67,
    completedCount: 52,
    qualifiedCount: 31,
    lastActivityAt: '2026-02-08T09:15:00Z',
    linkedCandidates: [
      { candidateId: 'cand-1', candidateName: 'Jan Janssen', email: 'jan.janssen@email.com', phone: '+32 470 12 34 56', applicationStatus: 'applied', score: null, appliedAt: '2026-02-10T10:30:00Z', channel: 'cv' },
      { candidateId: 'cand-4', candidateName: 'Sarah Van Den Berg', email: 'sarah.vdb@email.com', phone: '+32 473 45 67 89', applicationStatus: 'submitted', score: 78, appliedAt: '2025-11-10T09:15:00Z', channel: 'cv' },
      { candidateId: 'cand-8', candidateName: 'Emma Claessens', email: 'emma.claessens@email.com', phone: '+32 477 89 01 23', applicationStatus: 'applied', score: null, appliedAt: '2026-02-06T14:30:00Z', channel: 'whatsapp' },
    ],
    events: [
      { id: 'ev-v3-1', type: 'created', title: 'Vacature aangemaakt', timestamp: '2026-02-01T00:00:00Z' },
      { id: 'ev-v3-2', type: 'screening_configured', title: 'Pre-screening geconfigureerd', timestamp: '2026-02-01T11:00:00Z' },
      { id: 'ev-v3-3', type: 'published', title: 'Vacature online gezet', timestamp: '2026-02-02T09:00:00Z' },
      { id: 'ev-v3-4', type: 'candidate_applied', title: 'Kandidaat gesolliciteerd', candidateId: 'cand-4', candidateName: 'Sarah Van Den Berg', timestamp: '2025-11-10T09:15:00Z' },
      { id: 'ev-v3-5', type: 'candidate_qualified', title: 'Kandidaat gekwalificeerd', candidateId: 'cand-4', candidateName: 'Sarah Van Den Berg', description: 'Score: 78/100', timestamp: '2025-11-10T09:30:00Z' },
      { id: 'ev-v3-6', type: 'candidate_submitted', title: 'Kandidaat voorgesteld', candidateId: 'cand-4', candidateName: 'Sarah Van Den Berg', timestamp: '2026-02-05T14:00:00Z' },
      { id: 'ev-v3-7', type: 'candidate_applied', title: 'Kandidaat gesolliciteerd', candidateId: 'cand-8', candidateName: 'Emma Claessens', timestamp: '2026-02-06T14:30:00Z' },
      { id: 'ev-v3-8', type: 'candidate_applied', title: 'Kandidaat gesolliciteerd', candidateId: 'cand-1', candidateName: 'Jan Janssen', timestamp: '2026-02-10T10:30:00Z' },
    ],
  },
  {
    id: 'v4',
    title: 'Productie Operator',
    company: 'ITZU Brugge',
    location: 'Brugge',
    description: 'Operator voor productielijnen in ploegensysteem',
    status: 'screening_active',
    createdAt: '2026-02-05T00:00:00Z',
    hasScreening: true,
    hasOnboarding: false,
    isOnline: false,
    channels: { voice: true, whatsapp: true, cv: true },
    candidatesCount: 23,
    completedCount: 19,
    qualifiedCount: 12,
    lastActivityAt: '2026-02-07T16:35:00Z',
    linkedCandidates: [
      { candidateId: 'cand-6', candidateName: 'Lisa Martens', email: 'lisa.martens@email.com', phone: '+32 475 67 89 01', applicationStatus: 'submitted', score: 88, appliedAt: '2025-09-01T10:15:00Z', channel: 'whatsapp' },
    ],
    events: [
      { id: 'ev-v4-1', type: 'created', title: 'Vacature aangemaakt', timestamp: '2026-02-05T00:00:00Z' },
      { id: 'ev-v4-2', type: 'screening_configured', title: 'Pre-screening geconfigureerd', timestamp: '2026-02-05T10:00:00Z' },
      { id: 'ev-v4-3', type: 'published', title: 'Vacature online gezet', timestamp: '2026-02-05T14:00:00Z' },
      { id: 'ev-v4-4', type: 'candidate_applied', title: 'Kandidaat gesolliciteerd', candidateId: 'cand-6', candidateName: 'Lisa Martens', timestamp: '2025-09-01T10:15:00Z' },
      { id: 'ev-v4-5', type: 'candidate_qualified', title: 'Kandidaat gekwalificeerd', candidateId: 'cand-6', candidateName: 'Lisa Martens', description: 'Score: 88/100', timestamp: '2025-09-01T10:45:00Z' },
      { id: 'ev-v4-6', type: 'note_added', title: 'Notitie toegevoegd', description: 'Ervaren operator met technische achtergrond', timestamp: '2025-09-02T09:00:00Z' },
      { id: 'ev-v4-7', type: 'candidate_submitted', title: 'Kandidaat voorgesteld', candidateId: 'cand-6', candidateName: 'Lisa Martens', timestamp: '2026-02-07T16:35:00Z' },
      { id: 'ev-v4-8', type: 'unpublished', title: 'Vacature offline gezet', description: 'Voldoende kandidaten', timestamp: '2026-02-08T09:00:00Z' },
    ],
  },
  {
    id: 'v5',
    title: 'Inpakker',
    company: 'ITZU Mechelen',
    location: 'Mechelen',
    description: 'Inpakker voor food industrie',
    status: 'draft',
    createdAt: '2026-02-10T00:00:00Z',
    hasScreening: true,
    hasOnboarding: false,
    isOnline: null,
    channels: { voice: false, whatsapp: true, cv: false },
    candidatesCount: 0,
    completedCount: 0,
    qualifiedCount: 0,
    linkedCandidates: [
      { candidateId: 'cand-4', candidateName: 'Sarah Van Den Berg', email: 'sarah.vdb@email.com', phone: '+32 473 45 67 89', applicationStatus: 'applied', score: null, appliedAt: '2026-02-08T09:15:00Z', channel: 'whatsapp' },
      { candidateId: 'cand-8', candidateName: 'Emma Claessens', email: 'emma.claessens@email.com', phone: '+32 477 89 01 23', applicationStatus: 'submitted', score: 91, appliedAt: '2025-08-20T09:30:00Z', channel: 'cv' },
    ],
    events: [
      { id: 'ev-v5-1', type: 'created', title: 'Vacature aangemaakt', timestamp: '2026-02-10T00:00:00Z' },
      { id: 'ev-v5-2', type: 'screening_configured', title: 'Pre-screening geconfigureerd', timestamp: '2026-02-10T11:00:00Z' },
      { id: 'ev-v5-3', type: 'candidate_applied', title: 'Kandidaat gesolliciteerd', candidateId: 'cand-8', candidateName: 'Emma Claessens', timestamp: '2025-08-20T09:30:00Z' },
      { id: 'ev-v5-4', type: 'candidate_qualified', title: 'Kandidaat gekwalificeerd', candidateId: 'cand-8', candidateName: 'Emma Claessens', description: 'Score: 91/100', timestamp: '2025-08-20T10:00:00Z' },
      { id: 'ev-v5-5', type: 'candidate_submitted', title: 'Kandidaat voorgesteld', candidateId: 'cand-8', candidateName: 'Emma Claessens', timestamp: '2025-09-01T09:00:00Z' },
      { id: 'ev-v5-6', type: 'candidate_applied', title: 'Kandidaat gesolliciteerd', candidateId: 'cand-4', candidateName: 'Sarah Van Den Berg', timestamp: '2026-02-08T09:15:00Z' },
    ],
  },
  {
    id: 'v6',
    title: 'Administratief Bediende',
    company: 'ITZU Leuven',
    location: 'Leuven',
    description: 'Administratief medewerker voor HR afdeling',
    status: 'new',
    createdAt: '2026-02-11T00:00:00Z',
    hasScreening: false,
    hasOnboarding: false,
    isOnline: null,
    channels: { voice: false, whatsapp: false, cv: false },
    candidatesCount: 0,
    completedCount: 0,
    qualifiedCount: 0,
    linkedCandidates: [
      { candidateId: 'cand-7', candidateName: 'Kevin Van Damme', email: 'kevin.vd@email.com', phone: '+32 476 78 90 12', applicationStatus: 'rejected', score: 65, appliedAt: '2025-04-15T08:30:00Z', channel: 'cv' },
    ],
    events: [
      { id: 'ev-v6-1', type: 'created', title: 'Vacature aangemaakt', timestamp: '2026-02-11T00:00:00Z' },
      { id: 'ev-v6-2', type: 'candidate_applied', title: 'Kandidaat gesolliciteerd', candidateId: 'cand-7', candidateName: 'Kevin Van Damme', timestamp: '2025-04-15T08:30:00Z' },
      { id: 'ev-v6-3', type: 'candidate_qualified', title: 'Kandidaat gekwalificeerd', candidateId: 'cand-7', candidateName: 'Kevin Van Damme', description: 'Score: 65/100', timestamp: '2025-04-15T09:00:00Z' },
      { id: 'ev-v6-4', type: 'candidate_rejected', title: 'Kandidaat afgewezen', candidateId: 'cand-7', candidateName: 'Kevin Van Damme', description: 'Onvoldoende technische vaardigheden', timestamp: '2026-01-20T10:00:00Z' },
    ],
  },
];

// Mock clients (matching API fixtures)
export const mockClients: APIClient[] = [
  {
    id: 'client-1',
    name: 'Vandemoortele',
    location: 'Gent, België',
    industry: 'Voeding',
    logo: '/companies/vandmoortele.png',
    contact_name: 'Marie Peeters',
    contact_email: 'hr@vandemoortele.com',
    contact_phone: '+32 9 234 56 78',
    created_at: '2025-06-15T00:00:00Z',
    updated_at: '2026-02-10T10:30:00Z',
    active_vacancies: 5,
    total_candidates: 127,
  },
  {
    id: 'client-2',
    name: 'Agristo',
    location: 'Harelbeke, België',
    industry: 'Voeding',
    logo: '/companies/agristo.png',
    contact_name: 'Jan Vermeersch',
    contact_email: 'jobs@agristo.com',
    contact_phone: '+32 56 12 34 56',
    created_at: '2025-07-20T00:00:00Z',
    updated_at: '2026-02-09T14:25:00Z',
    active_vacancies: 3,
    total_candidates: 89,
  },
  {
    id: 'client-3',
    name: 'Colruyt Group',
    location: 'Halle, België',
    industry: 'Retail',
    logo: '/companies/colruyt_group.png',
    contact_name: 'Els Janssen',
    contact_email: 'recruitment@colruyt.be',
    contact_phone: '+32 2 345 67 89',
    created_at: '2025-05-01T00:00:00Z',
    updated_at: '2026-02-08T09:15:00Z',
    active_vacancies: 8,
    total_candidates: 234,
  },
  {
    id: 'client-4',
    name: 'Essers',
    location: 'Genk, België',
    industry: 'Logistiek',
    logo: '/companies/essers.png',
    contact_name: 'Peter Desmet',
    contact_email: 'hr@essers.com',
    contact_phone: '+32 89 12 34 56',
    created_at: '2025-09-10T00:00:00Z',
    updated_at: '2026-02-07T16:35:00Z',
    active_vacancies: 4,
    total_candidates: 156,
  },
  {
    id: 'client-5',
    name: 'Nike Laakdal',
    location: 'Laakdal, België',
    industry: 'Logistiek',
    contact_name: 'Anna Claes',
    contact_email: 'jobs@nike-laakdal.be',
    contact_phone: '+32 13 78 90 12',
    created_at: '2025-08-05T00:00:00Z',
    updated_at: '2026-02-06T11:20:00Z',
    active_vacancies: 6,
    total_candidates: 198,
  },
  {
    id: 'client-6',
    name: 'McDonalds Genk',
    location: 'Genk, België',
    industry: 'Horeca',
    logo: '/companies/mcdonalds.png',
    contact_name: 'Koen Maes',
    contact_email: 'jobs@mcdonalds-genk.be',
    contact_phone: '+32 89 34 56 78',
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-02-05T09:45:00Z',
    active_vacancies: 2,
    total_candidates: 45,
  },
  {
    id: 'client-7',
    name: 'Intern',
    location: 'België',
    industry: 'Intern',
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2026-02-11T00:00:00Z',
    active_vacancies: 1,
    total_candidates: 12,
  },
];
